In [5]:
# Copyright (c) 2019 Skymind AI Bhd.
# Copyright (c) 2020 CertifAI Sdn. Bhd.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

# NumPy Quickstart 

We will use the **Numpy** module to create and apply mathematical operations on matrices.

In [6]:
import numpy as np

Create a simple array of integers

In [7]:
array_1d = np.arange(0, 10)

The function `arange` creates an array from `range(0,10)`. The `arange()` function is similar to that of Python's `range()`.

In [8]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a $2\times2$ matrix. (2-dimensional array)

In [9]:
array_2d = np.array([[1, 2], [3, 4]])

In [10]:
array_2d

array([[1, 2],
       [3, 4]])

Create a $3\times 3$ matrix.

In [11]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Perform addition of two $3\times 3$ matrices.

In [13]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [14]:
print(np.add(matrixA,matrixB))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


Perform subtraction of two $3\times 3$ matrices.

In [15]:
matrixA = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [16]:
print(np.subtract(matrixA, matrixB))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Perform a Dot Product between 2 matrices.

Remember the rule that the matrix product of a matrix $A$ of shape $m \times n$ with a matrix $B$ of shape $n \times o$ has shape $m \times o$. 

In [17]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixA

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
matrixB = np.array([[1, 1], [1, 1], [1, 1]])
matrixB

array([[1, 1],
       [1, 1],
       [1, 1]])

In [19]:
print(np.matmul(matrixA, matrixB))

[[3 3]
 [3 3]
 [3 3]]


The dot product of a $3\times 3$ matrix with a $3\times 2$ matric is a $3\times 2$ matrix.

Generate a $3\times 3$ matrix with all zeros.

In [20]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Generate a $3\times 3$ matrix with all ones.

In [21]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Create a 3D tensor.

In [23]:
tensor_3d = np.array([[[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]],
                      [[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]]
                     ])

In [24]:
tensor_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [25]:
tensor_3d.shape

(2, 3, 4)

The shape of the tensor is described as **Width * Rows * Columns**.

Below is an example of a 4-dimension tensor, or a tensor of `rank 4`.

In [26]:
tensor_4 = np.array([[[[1,2,3,7],
                       [1,3,5,0],
                       [2,3,4,4]],
                      [[2,3,4,6],
                       [6,3,4,8],
                       [4,6,0,7]]],
                     [[[1,2,6,9],
                       [2,3,4,3],
                       [7,4,4,3]],
                      [[2,6,4,3],
                       [7,3,4,2],
                       [8,5,6,8]]]])

Using the `shape` attribute, we can see the magnitude of dimensions of said tensor.<br><br>
A $n$-dimension tensor will display a number of $n$ magnitudes. We can also use `ndim` to show the rank(dimension) of the tensor.

In [27]:
print(tensor_4.shape)
print(tensor_4.ndim)

(2, 2, 3, 4)
4


## Common functions to operate on NumPy arrays

In [28]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Check the shape of the array `array_3x3`.

In [29]:
array_3x3.shape

(3, 3)

Flatten `array_3x3`. Flatten will reduce any array of any dimensions into a 1-dimension array.

In [30]:
flattened_arr = array_3x3.ravel()

In [31]:
flattened_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
flattened_arr.shape

(9,)

**Use the `.copy()` method to clone the matrix instead of doing a reference.**

In [33]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`matrixB` is a reference to `matrixA`. `matrixC` is a copy of `matrixA`.

In [34]:
matrixB = matrixA 
matrixB

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
matrixC = np.copy(matrixA)

In [36]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
matrixA[0] = [99, 99, 99]

In [38]:
matrixA

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [39]:
matrixB

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [40]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that when we modify `matrixA`, `matrixB` changes, but not `matrixC`.

## Array Manipulation

**Perform vertical stack for 2 matrices using `numpy.vstack`.**

In [41]:
matrixA = np.zeros((3, 3))
matrixA

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
matrixB = np.ones((3, 3))
matrixB

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
vstack_matrix = np.vstack((matrixA, matrixB))
vstack_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
vstack_matrix.shape

(6, 3)

**Perform horizontal stack for 2 matrices using `numpy.hstack`.**

In [45]:
hstack_matrix = np.hstack((matrixA, matrixB))
hstack_matrix

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [46]:
hstack_matrix.shape

(3, 6)

**Perform depth stack for 2 matrices using `numpy.dstack`.**

In [49]:
matrixA = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
matrixB = np.array([[10, 20, 30],
                    [40, 50, 60], 
                    [70, 80, 90]])

In [48]:
dstack_matrix = np.dstack((matrixA, matrixB))
dstack_matrix

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]]])

In [50]:
dstack_matrix.shape

(3, 3, 2)

( \# of rows, \# of cols, \# of matrices )

In [52]:
matrixC = np.array([[1, 2],
                    [4, 5],
                    [7, 8]])
matrixD = np.array([[10, 20],
                    [40, 50], 
                    [70, 80]])
matrixE = np.array([[11, 12],
                    [13, 14],
                    [15, 16]])
np.dstack((matrixC, matrixD, matrixE)).shape

(3, 2, 3)

**Transpose a matrix.**

In [53]:
matrixC = np.transpose(matrixA)
matrixC

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Reshape a matrix into the assigned row x column.**

In [54]:
matrixC = matrixA.reshape(1, 9)
matrixC

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**Split a matrix vertically at the n-th index to 2 equal-sized subarrays.**

In [55]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [56]:
matrixC = np.vsplit(matrixA, 2)
matrixC

[array([[0, 0, 0],
        [0, 0, 0]]),
 array([[1, 1, 1],
        [1, 1, 1]])]

**Split a matrix horizontally into 3 equal-sized subarrays.**

In [57]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [58]:
matrixC = np.hsplit(matrixA, 3)
matrixC

[array([[0],
        [0],
        [1],
        [1]]),
 array([[0],
        [0],
        [1],
        [1]]),
 array([[0],
        [0],
        [1],
        [1]])]

In [62]:
matrixD = np.array([[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1]])
np.vsplit(np.hsplit(matrixD, 2)[0], 2)[1]

array([[1, 1],
       [1, 1]])

## Exercise

Create a $5\times 3$ matrix populated with random samples from a uniform distribution and name it **`mat_1`**.

*hint: `numpy.random.rand`*

In [64]:
mat_1 = np.random.rand(5, 3)
mat_1

array([[0.78250013, 0.27299896, 0.97569078],
       [0.99922498, 0.70970729, 0.73890996],
       [0.23595503, 0.46922848, 0.80317497],
       [0.93872904, 0.01609809, 0.91603577],
       [0.84564877, 0.62262794, 0.56199918]])

Create a matrix **`mat_2`** of any size. The matrix should be eligible to perform matrix multiplication with `mat_1`.

In [66]:
mat_2 = np.random.rand(3, 2)
mat_2

array([[0.53385238, 0.41147685],
       [0.7061562 , 0.52371518],
       [0.99310277, 0.23405826]])

Perform matrix multiplication of `mat_1` and `mat_2` and store it in variable **`mat_3`**.

In [68]:
mat_3 = np.matmul(mat_1, mat_2)
mat_3

array([[1.57948068, 0.69332287],
       [1.76841637, 0.95579041],
       [1.25494905, 0.53082185],
       [1.42222815, 0.60910182],
       [1.44924714, 0.80558515]])

Create another matrix that has the same number of columns as `mat_3` and name it **`mat_4`**

In [69]:
mat_4 = np.random.rand(2, 2)
mat_4

array([[0.12007054, 0.95022267],
       [0.82414042, 0.12387058]])

Stack matrix `mat_3` and `mat_4` vertically. Name the result **`mat_5`**.

In [71]:
mat_5 = np.vstack((mat_3, mat_4))
mat_5

array([[1.57948068, 0.69332287],
       [1.76841637, 0.95579041],
       [1.25494905, 0.53082185],
       [1.42222815, 0.60910182],
       [1.44924714, 0.80558515],
       [0.12007054, 0.95022267],
       [0.82414042, 0.12387058]])

Transpose `mat_5` and name the transposed matrix **`mat_6`**.

In [72]:
mat_6 = np.transpose(mat_5)
mat_6

array([[1.57948068, 1.76841637, 1.25494905, 1.42222815, 1.44924714,
        0.12007054, 0.82414042],
       [0.69332287, 0.95579041, 0.53082185, 0.60910182, 0.80558515,
        0.95022267, 0.12387058]])

Check the shape of **`mat_6`**.

In [73]:
mat_6.shape

(2, 7)

Vertically split **`mat_6`** into two subarrays.

In [74]:
np.vsplit(mat_6, 2)

[array([[1.57948068, 1.76841637, 1.25494905, 1.42222815, 1.44924714,
         0.12007054, 0.82414042]]),
 array([[0.69332287, 0.95579041, 0.53082185, 0.60910182, 0.80558515,
         0.95022267, 0.12387058]])]